export const PROJECTS = [
  {
    id: "ods-form",
    name: "ODS Form",
    fullName: "Online Data System Form",
    brand: "KEMENKOP (Ministry Of Cooperatives)",
    ledBy: "Akbar Dhia",
    roles: "Full Stack Development",
    year: "2025",
    description: "A fail-safe custom form builder natively integrated with ODS Mandiri to track cooperative profiles in real-time and eliminate data gaps.",
    location: 'Jakarta, Indonesia',
    category: ['Web', 'Backend'],
    tech: ["React", "Tailwind", "Laravel"],
    status: "LIVE",
    accentColor: "#4A7EF5",
    preview: "/projects/odsform.png",
    link: "odsform.kop.go.id",
  },
  {
    id: "manager-usaha-v2",
    name: "Manager Usaha V2",
    fullName: "Manager Usaha",
    brand: "Manager Usaha",
    ledBy: "AkbarD",
    roles: "Mobile Development",
    year: "2024",
    description: "Business metrics & inventory automation with on-device Machine Learning classification. A comprehensive tool for small business owners to manage their stock and financial health with minimal manual entry.",
    location: 'Bogor, Indonesia',
    category: ['Android', 'Backend'],
    tech: ["Kotlin", "Laravel", "ML Kit"],
    status: "LIVE",
    accentColor: "#9CCC65",
    preview: "/Manager_usahav2.png",
    link: "",
  },
  {
    id: "cogito",
    name: "Cogito",
    fullName: "Cogito, Debate Companion",
    brand: "Cogito (AI Debate Platform)",
    ledBy: "AkbarD",
    roles: "AI Engineering",
    year: "2024",
    description: "AI debate companion that generates counter-arguments in real time. Designed to help users sharpen their rhetorical skills and explore multiple perspectives on any given topic.",
    location: 'Jakarta, Indonesia',
    category: ['AI', 'Backend', 'Android'],
    tech: ["Express", "PostgreSQL", "Kotlin", "Qwen"],
    status: "BETA",
    accentColor: "#AED581",
    preview: "/assets/projects/cogito.jpg",
    link: "https://github.com/LazyPota/Cogito/tree/main",
  },
  {
    id: "ods-mandiri",
    name: "ODS Mandiri",
    fullName: "Online Data System Mandiri",
    brand: "KEMENKOP (Ministry Of Cooperatives)",
    ledBy: "Kemenkop RI",
    roles: "Frontend Engineering",
    year: "2025",
    description: "National online data system for cooperatives—centralized data management, financial reporting (RAT), member profiles, and legal documentation. The backbone of cooperative data in Indonesia.",
    location: 'Jakarta, Indonesia',
    category: ['Web', 'Backend'],
    tech: ["React", "Laravel"],
    status: "LIVE",
    accentColor: "#C5E1A5",
    preview: "/ods-mandiri.png",
    link: "ods.kop.go.id",
  },
];
