export const PROJECTS = [
  {
    id: "ods-form",
    name: "ODS Form",
    fullName: "ODS Form, Custom Form Builder",
    brand: "KEMENKOP (Kementerian Koperasi)",
    ledBy: "Akbar Dhia",
    roles: "Full Stack Development",
    year: "2025",
    description: "A fail-safe custom form builder natively integrated with ODS Mandiri to track cooperative profiles in real-time and eliminate data gaps.",
    tech: ["React", "Tailwind", "Laravel"],
    status: "LIVE",
    accentColor: "#4A7EF5",
    preview: "/projects/odsform.png",
    link: "odsform.kop.go.id",
  },
  {
    id: "manager-usaha-v2",
    name: "Manager Usaha V2",
    fullName: "Manager Usaha",
    brand: "Manager Usaha",
    ledBy: "AkbarD",
    roles: "Mobile Development",
    year: "2024",
    description: "Business metrics & inventory automation with on-device Machine Learning classification. A comprehensive tool for small business owners to manage their stock and financial health with minimal manual entry.",
    tech: ["Kotlin", "Laravel", "ML Kit"],
    status: "LIVE",
    accentColor: "#9CCC65",
    preview: "/Manager_usahav2.png",
    link: "",
  },
  {
    id: "cogito",
    name: "Cogito",
    fullName: "Cogito, Debate Companion",
    brand: "Cogito (AI Debate Platform)",
    ledBy: "AkbarD",
    roles: "AI Engineering",
    year: "2024",
    description: "AI debate companion that generates counter-arguments in real time. Designed to help users sharpen their rhetorical skills and explore multiple perspectives on any given topic.",
    tech: ["Express", "PostgreSQL", "Kotlin", "Qwen"],
    status: "BETA",
    accentColor: "#AED581",
    preview: "/assets/projects/cogito.jpg",
    link: "https://github.com/LazyPota/Cogito/tree/main",
  },
  {
    id: "sako",
    name: "Sako",
    fullName: "Sako, Simpan Pinjam",
    brand: "Sako (Cooperative Finance)",
    ledBy: "AkbarD",
    roles: "Full Stack Development",
    year: "2023",
    description: "Simpan-pinjam assistant for cooperatives—payments, analytics, plus reporting. Digitizing traditional financial systems with a modern, secure, and accessible platform.",
    tech: ["React", "Laravel"],
    status: "BETA",
    accentColor: "#C5E1A5",
    preview: "/Sako-login.png",
    link: "",
  },
];
