import { PERSONAL_INFO } from '../../2025/constants/portfolioData';

export const CONFIG_2026 = {
  social: [
    { name: 'Email', url: `mailto:${PERSONAL_INFO.email}` },
    { name: 'LinkedIn', url: `https://linkedin.com/in/${PERSONAL_INFO.linkedin}` },
    { name: 'GitHub', url: `https://github.com/akbrdhia` },
    { name: 'Instagram', url: 'https://www.instagram.com/bukan__akbarr/' },
    { name: 'Blog', url: 'https://blog.akbardhia.me' }
  ],
  nav: [
    { name: 'Home', path: '/2026' },
    { name: 'About', path: '/2026/about' },
    { name: 'Projects', path: '/2026/projects' },
    { name: 'Contact', path: '/2026/contact' }
  ],
  location: PERSONAL_INFO.location,
  timezone: 'Western Indonesian Time',
  skills: {
    nodes: [
      { id: 'kotlin', name: 'Kotlin', category: 'mobile' },
      { id: 'android', name: 'Android', category: 'mobile' },
      { id: 'flutter', name: 'Flutter', category: 'mobile' },
      { id: 'dart', name: 'Dart', category: 'mobile' },
      { id: 'react', name: 'React', category: 'frontend' },
      { id: 'nextjs', name: 'Next.js', category: 'frontend' },
      { id: 'tailwind', name: 'Tailwind', category: 'frontend' },
      { id: 'typescript', name: 'TypeScript', category: 'frontend' },
      { id: 'javascript', name: 'JavaScript', category: 'frontend' },
      { id: 'framer', name: 'Framer', category: 'frontend' },
      { id: 'laravel', name: 'Laravel', category: 'backend' },
      { id: 'express', name: 'Express', category: 'backend' },
      { id: 'nodejs', name: 'Node.js', category: 'backend' },
      { id: 'go', name: 'Go', category: 'backend' },
      { id: 'php', name: 'PHP', category: 'backend' },
      { id: 'python', name: 'Python', category: 'backend' },
      { id: 'prisma', name: 'Prisma', category: 'backend' },
      { id: 'mysql', name: 'MySQL', category: 'database' },
      { id: 'postgres', name: 'PostgreSQL', category: 'database' },
      { id: 'sqlserver', name: 'SQL Server', category: 'database' },
      { id: 'roomdb', name: 'Room DB', category: 'database' },
      { id: 'redis', name: 'Redis', category: 'database' },
      { id: 'docker', name: 'Docker', category: 'tools' },
      { id: 'git', name: 'Git', category: 'tools' },
      { id: 'figma', name: 'Figma', category: 'tools' },
    ],
    links: [
      { source: 'kotlin', target: 'android' },
      { source: 'flutter', target: 'dart' },
      { source: 'react', target: 'nextjs' },
      { source: 'react', target: 'tailwind' },
      { source: 'react', target: 'typescript' },
      { source: 'react', target: 'framer' },
      { source: 'nextjs', target: 'typescript' },
      { source: 'nextjs', target: 'tailwind' },
      { source: 'javascript', target: 'typescript' },
      { source: 'javascript', target: 'react' },
      { source: 'javascript', target: 'nodejs' },
      { source: 'nodejs', target: 'express' },
      { source: 'nodejs', target: 'prisma' },
      { source: 'express', target: 'prisma' },
      { source: 'express', target: 'mysql' },
      { source: 'prisma', target: 'mysql' },
      { source: 'prisma', target: 'postgres' },
      { source: 'laravel', target: 'mysql' },
      { source: 'laravel', target: 'php' },
      { source: 'laravel', target: 'react' },
      { source: 'go', target: 'docker' },
      { source: 'docker', target: 'mysql' },
      { source: 'docker', target: 'postgres' },
      { source: 'python', target: 'docker' },
      { source: 'flutter', target: 'dart' },
      { source: 'git', target: 'docker' },
      { source: 'redis', target: 'nodejs' },
      { source: 'figma', target: 'react' },
      { source: 'kotlin', target: 'react' },
    ],
  },
  experience: [
    {
      year: '2023-2026',
      company: 'SMK',
      role: 'RPL (Rekayasa Perangkat Lunak) Student',
      tech: 'Kotlin, Python, React, Laravel, Java, C#, MySQL, PostgreSQL, Docker, Git',
      items: [
        'Built Manager Usaha — final project: business inventory app with on-device ML',
        'Built Cogito — AI debate companion for hackathon',
        'Built Download Organizer — CLI tool for file management',
      ],
    },
    {
      year: '2025',
      company: 'KEMENKOP RI',
      role: 'Intern Mobile Developer',
      tech: 'Laravel, React, SQLServer, MySQL, Docker',
      items: [
        'Built ODS Form — custom form builder for cooperative profiles',
        'Worked on ODS Mandiri — national cooperative data system',
        'Developed internal tools with Laravel',
      ],
    },
    {
      year: '2026',
      company: 'Solera',
      role: 'Fullstack Developer',
      tech: 'Next.js, Express, Prisma, MySQL, Docker',
      items: [
        'Built school ecosystem super-app — closed-loop fintech, marketplace, community platform',
        'Integrated multiple payment gateways (Midtrans, Xendit, Tripay)',
      ],
    },
  ],
};
